# wrapper 渲染与 CLI 面:
#   upstreamSubcommands  上游子命令集(bin.js 的 program.command 注册自动提取)
#   renderCompletion     bash 补全(静态名单,零运行时开销)
#   renderWrapper        主 wrapper(settings yq-merge/secret 注入/子命令分发)
{ lib, renderSettings, secretEnv, applyPlugins }:

let
  inherit (lib)
    concatStringsSep
    escapeShellArg
    filter
    getExe
    mapAttrsToList
    optionalString
    ;

  # 上游 CLI 子命令集(自动):commander 在 bin.js 的注册模式
  # program.command("<name>")。上游加子命令自动进保留集;
  # 文件缺失(非 dsh 包/测试 stub)回落内置名单;文件在但零匹配 →
  # throw(上游布局变化,fail-loud 提示更新此处正则)
  upstreamSubcommands = package:
    let
      binJs = "${toString package}/lib/bin.js";
      fallback = [ "web" "plugin" ];
    in
    if !builtins.pathExists binJs then fallback
    else
      let
        parts = builtins.split ''program\.command\("''
          (builtins.readFile binJs);
        cmds = lib.filter (c: c != null) (
          map
            (p: if builtins.isString p
              then builtins.match ''([a-z0-9-]+)".*'' p
              else null)
            parts
        );
        names = lib.flatten cmds;
      in
      if names == [ ] then
        throw "nixdsh: upstream dsh CLI layout changed (no program.command registrations in ${binJs}); update upstreamSubcommands in lib/wrapper.nix"
      else lib.unique names;

  # bash 补全(bash-completion 的 XDG_DATA_HOME 用户目录约定):
  # $1 位置补全 = 子命令分发名单 + 上游 web/plugin;--profile 值补全 =
  # 全部 profiles(含 web)。flags 不猜(各 app 自带 --help,launcher
  # allowUnknownOption 透传)。名单 build 期静态 → 补全零运行时开销
  renderCompletion =
    {
      name ? "dsh",
      subcommands ? [ ],   # 可分发的 profile 子命令(不含 web)
      profiles ? [ ],      # --profile 合法值(含 web)
      upstream ? [ ],      # 上游子命令(web/plugin)
    }:
    let
      wordList = concatStringsSep " " (lib.unique (subcommands ++ upstream));
      profileList = concatStringsSep " " (lib.unique (profiles ++ upstream));
    in
    ''
      # generated by nixdsh — subcommand dispatch: dsh <profile> ≡ dsh --profile <profile>
      _dsh() {
        local cur prev
        cur="''${COMP_WORDS[COMP_CWORD]}"
        prev="''${COMP_WORDS[COMP_CWORD-1]}"
        if [ "$COMP_CWORD" -eq 1 ] && [[ "$cur" != -* ]]; then
          COMPREPLY=( $(compgen -W "${wordList}" -- "$cur") )
          return
        fi
        if [ "$prev" = "--profile" ]; then
          COMPREPLY=( $(compgen -W "${profileList}" -- "$cur") )
          return
        fi
      }
      complete -F _dsh ${name}
    '';

  # wrapper 渲染(TonyWu20 的 yq-merge 语义 + DSH_HOME):
  # - 声明 settings 每次启动 merge 进 settings.yaml:声明值覆盖同名键,本地其他键保留
  #   (dsh Web UI 会运行时改配置,yq merge 是唯一不与之打架的声明式方案)
  # - profile 子命令分发:dsh <profile> ... → dsh --profile <profile> ...(上游
  #   CLI 子命令集封闭 {web,plugin},`dsh web` 即官方的 profile-子命令样板,
  #   第三方 face 无入口,wrapper 层补同形态;名单含手写 profiles + 自动
  #   face,用户零声明)。web 排除:上游原生子命令已等价 boot profiles.web;
  #   其余撞上游子命令 → throw(拦截上游命令语义,如 plugin 的 pnpm 管理)
  # - profile 注入:调用无显式 --profile 且非 web/plugin 子命令(它们拒绝父级 --profile)时
  #   自动补 --profile <name>;fixedProfile 非 null 时强制绑定该 profile
  #   (face 分发改写后 --profile 已显式存在,注入逻辑自然跳过)
  renderWrapper =
    {
      cfg,
      pkgs,
      name ? "dsh",
      fixedProfile ? null,
      subcommands ? [ ],
    }:
    let
      effectiveProfile = if fixedProfile != null then fixedProfile else cfg.defaultProfile;
      # webSearch/llmDeepseek 不随 inherit:renderSettings 缺省 null,
      # stub cfg(无该键)与真实 cfg(默认 null)等价;显式 attrs 时模块
      # 系统保证键存在,inherit (cfg) 反而会炸 stub 调用方
      # 默认 preset 协调参数来自 applyPlugins(per-face 生效时全局
      # 不进 settings);stub cfg 或缺省键时 or 回落
      rsArgs = {
        inherit (cfg) settings telemetry providers defaultModel;
        webSearch = cfg.webSearch or null;
        webSearchProviders = cfg.webSearchProviders or { };
        llmDeepseek = cfg.llmDeepseek or null;
        webFetch = cfg.webFetch or null;
        webFetchProviders = cfg.webFetchProviders or { };
        defaultPreset = cfg.defaultPreset or null;
        hasFaceDefaultPreset = _applied.hasFaceDefaultPreset;
      };
      _applied = applyPlugins { inherit cfg pkgs; };
      settingsJSON =
        if renderSettings rsArgs == { } then null
        else builtins.toJSON (renderSettings rsArgs);
      settingsPrelude = optionalString (settingsJSON != null) ''
        dsh_home="''${DSH_HOME:-$HOME/.dsh}"

        if [ -L "$dsh_home/settings.yaml" ]; then
          rm "$dsh_home/settings.yaml"
        fi

        mkdir -p "$dsh_home"
        tmp="$(mktemp "$dsh_home/settings.yaml.XXXXXX")"

        if [ -f "$dsh_home/settings.yaml" ]; then
          ${getExe pkgs.yq-go} '. * load("${pkgs.writeText "dsh-settings.yaml" settingsJSON}")' \
            "$dsh_home/settings.yaml" > "$tmp"
        else
          cp ${escapeShellArg (toString (pkgs.writeText "dsh-settings.yaml" settingsJSON))} "$tmp"
        fi

        chmod 0600 "$tmp"

        if [ ! -f "$dsh_home/settings.yaml" ] || ! cmp -s "$tmp" "$dsh_home/settings.yaml"; then
          mv "$tmp" "$dsh_home/settings.yaml"
        else
          rm "$tmp"
        fi
      '';
      envPrelude = concatStringsSep "\n"
        (mapAttrsToList
          (n: v: "export ${n}=${escapeShellArg v}")
          cfg.environment);
      # secretFile 声明的 env 桥(文件 → 环境变量):每次 wrapper 调用现读,
      # 轮换即生效(优于 EnvironmentFile 的启动快照)。文件缺失 → 不 export,
      # provider 按请求报结构化错误(上游惰性设计,注册不看凭据)—— 与
      # MCP 通道 fail-loud 不同:那里 boot 必炸,这里 boot 不炸。
      # 先于 envPrelude:显式 cfg.environment 覆盖派生值
      secretEnvPrelude = concatStringsSep "\n"
        (mapAttrsToList
          (env: file: ''
            if [ -r ${escapeShellArg file} ]; then
              export ${env}="$(< ${escapeShellArg file})"
            fi'')
          (secretEnv { inherit cfg; }));
      # secret 注入块(mcpServers env/headers 占位符 → 真值):每次启动跑,
      # 轮换安全(secret 文件更新即生效);改动物化副本 patch 文件(用户
      # 目录,可 0600),store 工件永不含密钥。secret 文件缺失 → fail-loud
      # 退出,不静默带占位符启动。
      # 占位符清单 = mcpPatches 渲染行文本回收(单一事实源,防与渲染链
      # 漂移;insert 包裹后占位符在嵌套 config 里,扫整行 JSON)
      secretPrelude =
        let
          mcpRows = (applyPlugins { inherit cfg pkgs; }).mcpPatches;
          placeholders = lib.flatten
            (map
              (row:
                let m = builtins.match ".*(@dsh-secret:[^\"]*@).*" (builtins.toJSON row);
                in if m == null then [ ] else m)
              mcpRows);
        in
        optionalString (placeholders != [ ]) ''
          _secrets=(
          ${concatStringsSep "\n" (map (p: "  ${escapeShellArg p}") placeholders)}
          )
          for _pf in "$dsh_home"/profiles/*/cordis.patch.yml; do
            [ -f "$_pf" ] || continue
            _changed=0
            _tmp="$(mktemp "$_pf.XXXXXX")"
            cp "$_pf" "$_tmp"
            for _ph in "''${_secrets[@]}"; do
              if grep -qF "$_ph" "$_tmp"; then
                _path="$(printf '%s' "$_ph" | sed -e 's/^@dsh-secret://' -e 's/@$//')"
                if [ ! -r "$_path" ]; then
                  echo "dsh: secret file '$_path' (MCP placeholder) unreadable" >&2
                  rm -f "$_tmp"; exit 1
                fi
                ${getExe pkgs.replace-secret} "$_ph" "$_path" "$_tmp" || { rm -f "$_tmp"; exit 1; }
                _changed=1
              fi
            done
            if [ "$_changed" -eq 1 ]; then
              chmod 0600 "$_tmp"
              mv "$_tmp" "$_pf"
            else
              rm -f "$_tmp"
            fi
          done
        '';
      # 只给主 wrapper(fixedProfile = null)。仅拦 $1(与上游子命令同粒度),
      # -- 之后的位置参数不碰;web 排除(上游原生 web 子命令已等价 boot
      # profiles.web)。撞上游子命令(eval 期 throw,名单自动提取):
      # 上游子命令语义 ≠ profile boot(如 plugin 是 pnpm 管理),分发会
      # 静默拦截上游命令
      _clashAssert =
        let
          reserved = upstreamSubcommands cfg.package;
          clashing = filter (f: f != "web" && builtins.elem f reserved) subcommands;
        in
        if clashing != [ ] then
          throw "programs.dsh: profile/face names clash with upstream dsh subcommands (${concatStringsSep ", " clashing}; reserved: ${concatStringsSep ", " reserved}). Rename the profile or the face — dispatch would shadow the upstream command."
        else null;
      dispatchFaces = filter (f: f != "web") subcommands;
      faceDispatch =
        builtins.seq _clashAssert
          (optionalString (dispatchFaces != [ ]) ''
            if [ $# -gt 0 ]; then
              case "$1" in
                ${concatStringsSep "|" dispatchFaces})
                  _dsh_face="$1"
                  shift
                  set -- --profile "$_dsh_face" "$@"
                  ;;
              esac
            fi
          '');
      profilePrelude = optionalString (effectiveProfile != null) ''
        wants_profile=0
        is_subcommand=0
        for arg in "$@"; do
          case "$arg" in
            --) break ;;
            --profile) wants_profile=1 ;;
            --profile=*) wants_profile=1 ;;
            web|plugin) is_subcommand=1 ;;
          esac
        done

        if [ "$wants_profile" -eq 0 ] && [ "$is_subcommand" -eq 0 ]; then
          set -- --profile ${escapeShellArg effectiveProfile} "$@"
        fi
      '';
      argsStr = concatStringsSep " " (map escapeShellArg cfg.extraArgs);
    in
    pkgs.writeShellScriptBin name ''
      set -euo pipefail
      export DSH_HOME="${cfg.dshHome}"
      ${secretEnvPrelude}
      ${envPrelude}
      dsh_home="${cfg.dshHome}"
      ${secretPrelude}
      ${settingsPrelude}
      ${faceDispatch}
      ${profilePrelude}
      exec ${getExe cfg.package} ${argsStr} "$@"
    '';
in
{
  inherit upstreamSubcommands renderCompletion renderWrapper;
}
