# generated by nixdsh — subcommand dispatch: dsh <profile> ≡ dsh --profile <profile>
_dsh() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [ "$COMP_CWORD" -eq 1 ] && [[ "$cur" != -* ]]; then
    COMPREPLY=( $(compgen -W "tui headless web plugin" -- "$cur") )
    return
  fi
  if [ "$prev" = "--profile" ]; then
    COMPREPLY=( $(compgen -W "web tui headless plugin" -- "$cur") )
    return
  fi
}
complete -F _dsh dsh
